#!/bin/bash

# "merge" history from all active terms
export HISTFILESIZE=1000000000
export HISTSIZE=1000000

#### Terminal title
function printTermTitle {
    if [ -z "${TERM_TITLE}" ] ; then
        TITLE="$(basename "${PWD}")"
    else
        TITLE="${TERM_TITLE}"
    fi

    echo -ne "\033]0; ${TITLE} \007"
}

function setTermTitle {
    #if [ "${USER}" != "$(stat -c "%U" ~/.bashrc)" ] ; then
    #fi

    export TERM_TITLE="$*"
}

setTermTitle  # term title will be current basedir (at anytime).
# setTermTitle "$(pwd -P | xargs basename)"  # term title will be current basedir (at term creation)

#### history
# export PROMPT_COMMAND="history -a ; ${PROMPT_COMMAND}" # merge history of all the terminals
# "merge" history from all active terms
if ! grep history <<< "${PROMPT_COMMAND}" ; then
    export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND ;} history -a"  # equivalent to shopt -s histappend ?
    export PROMPT_COMMAND="setUserColor ; ${PROMPT_COMMAND}"  # merge history of all the terminals
    export PROMPT_COMMAND="printTermTitle ; ${PROMPT_COMMAND}"  # set term title
fi

function historyHistogram {
    history|awk '{print $2}'|awk 'BEGIN {FS="|"} {print $1}'|sort|uniq -c|sort -nr
}


#### PROMPT colors and text
function setUserColor {
    if [ -z "${!USER}" ] ; then
        local USER_HASH
        USER_HASH=$(echo "${USER}" | md5sum | cut -f1 -d' ')
        local USER_NID
        # bc does not work with lowercase hexadecimal
        USER_NID=$(echo "obase=10; ibase=16; ${USER_HASH^^}" | bc)
        export "${USER}"="$(( USER_NID % 6 + 93 ))" # one color per user (up to 8 colors)
    fi
}

# change color prompt given exit code from the last command
#     format: user@hostname:current_pwd$
#             +------------+-----------+
#     color:  + usercolor  + green/red +
setUserColor
export PS1='\[\033['${!USER}'m\]\[\033[1m\]\u@\h:`if [[ $? = 0 ]]; then echo \[\033[32m\]; else echo \[\033[31m\]; fi`\w$\[\033[0m\] '

#### bat integration
export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
alias bat='batcat'

#### Enable programmable completion features
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
  source /etc/bash_completion
fi

#### Autojump <3
if [ -f /usr/share/autojump/autojump.bash ]; then
  source /usr/share/autojump/autojump.bash
fi

#### misc
export PATH=${PATH}:~/.local/bin # for python modules installed from pip3

export LESS=-R
alias open='xdg-open'

source /etc/profile.d/undistract-me.sh

function cheat() {
    curl "cheat.sh/${1}" | less
}

function lol() {
    exec 1> >(lolcat)
} 

function unlol() {
    exec 1> /dev/stdout
}
