" spaces instead tabs: https://softwareengineering.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e#:~:text=Use%20tabs%20to%20indent%20the%20start%20of%20the%20line%2C%20one,up%20regardless%20of%20tab%20size.
set tabstop=4 shiftwidth=4 expandtab
set showmatch

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Checkers
Plugin 'dense-analysis/ale'
Plugin 'rhysd/vim-grammarous'

" Beautifulers
Plugin 'itchyny/lightline.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'peterhoeg/vim-qml'
Plugin 'asciidoc/vim-asciidoc'
Plugin 'pangloss/vim-javascript'
Plugin 'joereynolds/sql-lint'
Plugin 'frazrepo/vim-rainbow'

" Versionning
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
" """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" NRB: TO RELOAD configuration file, type:
"      :so ~/.vim/vimrc
"
"      Don't forget to execute sometimes:
"      :PluginUpdate
"
"      Make sure to install tools:
"      sudo apt install python3-bashate pip3 cppcheck clang clang-tidy
"      python3 -m pip install cpplint
" """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let g:grammarous#default_comments_only_filetypes = {
            \ '*' : 1, 'help' : 0, 'markdown' : 0,
            \ }
